Fixes the interface callback group, a wrong service name and a crash.
tesseract-robotics/tesseract_ros2 pull request #41
Opened 2023-04-25 06:30 UTC by rjoomen

2023-05-04 18:45 UTC, rjoomen commented
Done, both Humble and Foxy build. @marrts / @Levi-Armstrong could you review the PR?

Sorry for the messy commit history, I had some issues getting clang-format happy and foxy to build. clang-format still isn't happy, but that seems a config issue, as on my PC it does format the parts with preprocessor code properly. And the clang-tidy workflow needs an update, I'm looking into that.

2023-05-10 21:00 UTC, marip8 commented
FWIW the `.run-clang-format` script is using [`clang-format-10`](https://github.com/tesseract-robotics/tesseract_ros2/blob/8c2644e8c65c903bb69c8ee07530080da75ba8a0/.run-clang-format#LL2C187-L2C187) which may or may not be the version of `clang-format` installed on your machine. I've noticed differences in what `clang-format-8` chooses to format vs `clang-format-10`, so maybe that's part of the issue

2023-05-25 16:49 UTC, marrts commented
I'm happy with this, but I'm not sure if @Levi-Armstrong or @marip8 have an opinion on the clang formatting being different. 

The only notable difference I see is now the switch-case statements have the `{` on the same line as the case statement rather than starting on a new line.

2023-05-25 20:49 UTC, Levi-Armstrong requested changes

2023-05-25 20:49 UTC, Levi-Armstrong commented on .clang-format
> -    AfterCaseLabel: 'true'
I would keep this the same to match all of Tesseract.

2023-05-26 05:30 UTC, rjoomen commented on .clang-format
> -    AfterCaseLabel: 'true'
The tesseract_ros2 .clang-format is exactly the same as the one from tesseract, tesseract_planning and trajopt. So removing this line would make it different.

2023-05-27 03:38 UTC, Levi-Armstrong approved these changes

2023-05-27 03:38 UTC, Levi-Armstrong commented
@marrts If your happy feel free to merge.

2023-05-27 03:39 UTC, merged